# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bimage.proto\"\x14\n\x05image\x12\x0b\n\x03png\x18\x01 \x01(\x0c\x32#\n\x06Rotate\x12\x19\n\x05rot90\x12\x06.image\x1a\x06.image\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='image',
  full_name='image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='png', full_name='image.png', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=35,
)

DESCRIPTOR.message_types_by_name['image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

image = _reflection.GeneratedProtocolMessageType('image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'image_pb2'
  # @@protoc_insertion_point(class_scope:image)
  ))
_sym_db.RegisterMessage(image)



_ROTATE = _descriptor.ServiceDescriptor(
  name='Rotate',
  full_name='Rotate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=37,
  serialized_end=72,
  methods=[
  _descriptor.MethodDescriptor(
    name='rot90',
    full_name='Rotate.rot90',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_IMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROTATE)

DESCRIPTOR.services_by_name['Rotate'] = _ROTATE

# @@protoc_insertion_point(module_scope)
